<?php

class KangxinItemCodes {
    const SICK_ID = 'PATIENT_ID';
    const SICK_NUM = 'MED_RECORD_NUM';
    const RESIDENCE_NO = 'RESIDENCE_NO';
    const AGE = 'ENROL_AGE';
    const CURRENT_ADDRESS = 'ADDRESS';
    const IDENTITY_NUMBER = 'NAT_ZH';
    const PHONE = 'PHONE';
    const CONTACT_NAME = 'ASSOCIATE_NAME';
    const RELATION = 'ASSOCIATE_RELATION';
    const CONTACT_PHONE = 'ASSOCIATE_PHONE';
    const ADMISSION_TIME = 'ADMISSION_TIME';
    const ADMISSION_DEPARTMENT = 'ADMISSION_DEPARTMENT';
    const ADMISSION_WARD = 'ADMISSION_WARD';
    const HOSPITAL_ADMISSION = 'HOSPITAL_ADMISSION';
    const DISCHARGE_TIME = 'DISCHARGE_TIME';
    const DISCHARGE_DEPARTMENT = 'DISCHARGE_DEPARTMENT';
    const DISCHARGE_WARD = 'DISCHARGE_WARD';
    const ACTUAL_HOSPITAL_DAYS = 'ACTUAL_HOSPITAL_DAYS';
    const DISCHARGE_DISEASE_CODE = 'DISCHARGE_DISEASE_CODE';
    const DISCHARGE_MAIN_DIAGNOSIS = 'DISCHARGE_MAIN_DIAG';
    const OTHER_DISEASE_CODES = 'OTHER_DISEASE_CODES';
    const DISCHARGE_OTHER_DIAGNOSES = 'DISCHARGE_OTHER_DIAG';
    const DRUG_ALLERGY = 'DRUG_ALLERGY';
    const DOCTOR = 'DOCTOR';
    const RESPONSIBLE_NURSE = 'RESPONSIBLE_NURSE';
    const HNTH_HOSPITAL = 'TOTAL_ADMISSIONS';
    const HOSPITALIZED = 'HOSPITALIZED';
    const DISCHARGE_SITUATION = 'DISCHARGE_SITUATION';
    const DISCHARGE_INSTRUCTIONS = 'DISCHARGE_INSTRUCT';
    const NOTES = 'NOTES';
    const SOURCE = 'SOURCE';

    // Procedure ITEM CODES
    const PROCEDURE_ARRAY = 'PROCEDURE_ARRAY';
    const OPERATION_DATE = 'OPERATION_DATE';
    const OPERATION_LEVEL = 'OPERATION_LEVEL';
    const OPERATION_SURGEON = 'OPERATION_SURGEON';
    const OPERATION_TYPE = 'OPERATION_TYPE';
    const OPERATION_CODE = 'OPERATION_CODE';
    const OPERATION_NAME = 'OPERATION_NAME';
    const OPERATION_NAME_1 = 'OPERATION_NOTES1';
    const OPERATION_NAME_2 = 'OPERATION_NOTES2';
    const OPERATION_NAME_3 = 'OPERATION_NOTES3';
    const OPERATION_NAME_4 = 'OPERATION_NOTES4';
}