<?php

class KangxinItemCodes {
    const SICK_ID = 'PATIENT_ID';
    const SICK_NUM = 'MED_RECORD_NUM';
    const ETHNICITY = 'ETHNICITY';
    const ETHNICITY_OPTIONS = 'ETHNICITY_OPTIONS';
    const ID_CARD = 'ID_CARD';
    const ID_CARD_TYPE = 'ID_CARD_TYPE';
    const PHONE = 'PHONE';
    const MARITAL = 'MARITAL_STATUS';
    const MARITAL_OPTIONS = 'MARITAL_STATUS_OPTIONS';
    const PATIENT_TYPE = 'PATIENT_TYPE';
    const PROFESSION = 'PROFESSION';
    const PROFESSION_OPTIONS = 'PROFESSION_OPTIONS';
    const CONTACT_NAME = 'ASSOCIATE_NAME';
    const RELATION = 'ASSOCIATE_RELATION';
    const RELATION_OPTIONS = 'ASSOCIATE_RELATION_OPTIONS';
    const RELATIONSHIP_CODE = 'RELATIONSHIP_CODE';
    const RELATIVE_FAMILY_CODE = 'RELATIVE_FAMILY_CODE';
    const CONTACT_PHONE = 'ASSOCIATE_PHONE';
    const ADMISSION_DIAG = 'ADMISSION_DIAG';
    const HOSPITAL_ADMISSION = 'HOSPITAL_ADMISSION';
    const DISCHARGE_DIAG = 'DISCHARGE_DIAG_NP';
    const DISCHARGE_MAIN_DIAGNOSIS_CODE = 'DISCHARGE_MAIN_DIAG_CODE';
    const DISCHARGE_MAIN_DIAGNOSIS = 'DISCHARGE_MAIN_DIAG';
    const DRUG_ALLERGY = 'DRUG_ALLERGY';
    const HOSPITALIZED = 'HOSPITALIZED';
    const DISCHARGE_SITUATION = 'DISCHARGE_SITUATION';
    const DISCHARGE_INSTRUCTIONS = 'DISCHARGE_INSTRUCT';
    const SOURCE = 'SOURCE';
    const LAST_UPDATE = 'LAST_UPDATE';
    const LAST_IMPORT = 'LAST_IMPORT';

    // Adamission info table
    const ADMISSION_INFO_TABLE = 'ADMISSION_INFO_TABLE';
    const RESIDENCE_NO = 'RESIDENCE_NO';
    const VISIT_NUMBER = 'VISIT_NUMBER';
    const ADMISSION_TIME = 'ADMISSION_TIME';
    const ADMISSION_DEPARTMENT = 'ADMISSION_DEPARTMENT';
    const DISCHARGE_TIME = 'DISCHARGE_TIME';
    const DISCHARGE_DEPARTMENT = 'DISCHARGE_DEPARTMENT';
    const DISCHARGE_STATUS = 'DISCHARGE_STATUS';
    const DISCHARGE_STATUS_OPTIONS = 'DISCHARGE_STATUS_OPTIONS';
    const DOCTOR = 'DOCTOR';
    const DOCTOR_CODE = 'DOCTOR_CODE';
    const RESPONSIBLE_NURSE = 'RESPONSIBLE_NURSE';
    const RESPONSIBLE_NURSE_CODE = 'RESPONSIBLE_NURSE_CODE';

    // Diagnosis ITEM CODES
    const DIAGNOSIS_ARRAY = 'DIAGNOSIS_ARRAY';
    const DISCHARGE_OTHER_DIAG_CODE = 'DISCHARGE_OTHER_DIAG_CODE';
    const DISCHARGE_OTHER_DIAGNOSES = 'DISCHARGE_OTHER_DIAG';

    // Procedure ITEM CODES
    const PROCEDURE_ARRAY = 'PROCEDURE_ARRAY';
    const OPERATION_ID = 'APPLY_OPERATION_NUM';
    const PROCESS_ORDER = 'OPERATION_ORDER';
    const OPERATION_DATE = 'OPERATION_DATE';
    const OPERATION_LEVEL = 'OPERATION_LEVEL';
    const OPERATION_DOCTOR = 'OPERATION_DOCTOR';
    const OPERATION_DOCTOR_CODE = 'OPERATION_DOCTOR_CODE';
    const OPERATION_TYPE = 'OPERATION_TYPE';
    const OPERATION_CODE = 'OPERATION_CODE';
    const OPERATION_NAME = 'OPERATION_NAME';
    const OPERATION_NAME_1 = 'OPERATION_NOTES1';
    const OPERATION_NAME_2 = 'OPERATION_NOTES2';
    const OPERATION_NAME_3 = 'OPERATION_NOTES3';
    const OPERATION_NAME_4 = 'OPERATION_NOTES4';
}

